package com.example.demo.demo.mapper;

import com.example.demo.demo.model.PmsProduct;
import com.example.demo.demo.model.PmsProductWithBLOBs;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface PmsProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     *
     * @mbg.generated Thu Aug 13 11:04:33 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     *
     * @mbg.generated Thu Aug 13 11:04:33 CST 2020
     */
    int insert(PmsProductWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     *
     * @mbg.generated Thu Aug 13 11:04:33 CST 2020
     */
    int insertSelective(PmsProductWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     *
     * @mbg.generated Thu Aug 13 11:04:33 CST 2020
     */
    PmsProductWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     *
     * @mbg.generated Thu Aug 13 11:04:33 CST 2020
     */
    int updateByPrimaryKeySelective(PmsProductWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     *
     * @mbg.generated Thu Aug 13 11:04:33 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(PmsProductWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     *
     * @mbg.generated Thu Aug 13 11:04:33 CST 2020
     */
    int updateByPrimaryKey(PmsProduct record);


    List<PmsProduct> selectAllProduct();
}